[DOPS-895] Feature/ci update
soramitsu/soranet-eth pull request #1
Opened 2020-03-10 09:32 UTC by Cre-eD

# Task
[DOPS-895]  Fix GitHub module.
## Changes
1. CI updated.

## Author
Signed-off-by: Dmitriy Creed <creed@soramitsu.co.jp>

2020-03-10 12:42 UTC, Mingela commented on deploy/docker-compose.eth.yml
> +    image: nexus.iroha.tech:19002/soranet/eth-deposit:develop
correct the port please?

2020-03-10 12:42 UTC, Mingela commented on deploy/docker-compose.eth.yml
> +    image: nexus.iroha.tech:19002/soranet/eth-testing-endpoints:develop
same here

2020-03-10 12:42 UTC, Mingela approved these changes

2020-03-10 14:33 UTC, kogeler requested changes
Fix ports

2020-03-10 15:08 UTC, ravenolf reviewed
Check bagdan comment

2020-03-11 06:28 UTC, BulatSaif commented on Jenkinsfile
>      skipDefaultCheckout()
```suggestion
```

2020-03-11 06:28 UTC, BulatSaif commented on Jenkinsfile
>            def scmVars = checkout scm
```suggestion
```

2020-03-11 06:30 UTC, BulatSaif commented on Jenkinsfile
>            def scmVars = checkout scm
```suggestion
```

2020-03-11 08:14 UTC, Mingela approved these changes

2020-03-12 10:41 UTC, ravenolf approved these changes

2020-03-12 10:48 UTC, BulatSaif approved these changes

2020-03-12 10:54 UTC, kogeler approved these changes
OK

2020-03-17 11:05 UTC, merged